apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronjobs.example.com
spec:
  group: example.com
  names:
    kind: CronJob
    plural: cronjobs
    singular: cronjob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                command:
                  type: array
                  items:
                    type: string
