version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3004:3004"
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "5004:5004"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5431/testdb

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5431:5431"
